### ISSUE TITLE
action部署失败，git push时提示无权限

### ISSUE THREAD

**Issue by lovexlc** [glink24/urodele#11]
您好，action部署的时候提示
remote: Invalid username or password.
看着是git push到ph-pages分支的时候没有权限，我看action对应的yaml文件里有access_token，是需要配置这个吗

**Comment by alucardzlh** [comment]
在仓库对应的 settings 中要配置 ACCESS_TOKEN
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/9d65dbcc-225a-4b98-a225-da1c2f86eb81">

**Comment by lovexlc** [comment]
谢谢，我找到您的博客中的教程，已经配置好了

Alucard·D·Zhang ***@***.***>于2024年12月6日 周五12:20写道：

**Comment by alucardzlh** [comment]
我看到你部署的urodele并没有实现登录，就有发布自己的文章，请问是如何做到的？
