### ISSUE TITLE
可否像哪吒面板那样校验GitHub用户名？

### ISSUE THREAD

**Issue by Jonnyan404** [glink24/urodele#2]

**Comment by glink25** [comment]
如果是指权限校验的话，目前做了简单的权限检测，只有对仓库有push权限的角色登录后才会看到编辑按钮

**Comment by Jonnyan404** [comment]
> 如果是指权限校验的话，目前做了简单的权限检测，只有对仓库有push权限的角色登录后才会看到编辑按钮

我是指登录，哪吒那里是配置文件指定github用户名，然后登录会转发到github校验是否符合。
你有空的话，安装体验一下应该就懂。

**Comment by glink25** [comment]
> > 如果是指权限校验的话，目前做了简单的权限检测，只有对仓库有push权限的角色登录后才会看到编辑按钮
> 
> 我是指登录，哪吒那里是配置文件指定github用户名，然后登录会转发到github校验是否符合。 你有空的话，安装体验一下应该就懂。

Mark as todo 了解，这里后面会禁止无权限的用户登录，目前虽然允许任意用户登录，但是实际上也是无法改动博客文章的

**Comment by glink24** [comment]
增加了不允许无权限用户登录功能
