### ISSUE TITLE
登录之后，没有编辑按钮？如何使用？

### ISSUE THREAD

**Issue by Jonnyan404** [glink24/urodele#3]

**Comment by glink25** [comment]
hi，在部署之前需要调整urodele.config.ts中的内容为自己的github repo配置，示例
[urodele.config.ts](https://github.com/glink25/glink25.github.io/blob/main/urodele.config.ts)
关于配置部分会继续补充详细的文档，感谢反馈～

**Comment by glink25** [comment]
[如何使用 | How to use](https://github.com/glink24/urodele?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
