### ISSUE TITLE
Applications OAuth 授权配置

### ISSUE THREAD

**Issue by alucardzlh** [glink24/urodele#8]
您好 

感觉你的项目很有意思，所以自己尝试玩了一下。

因前端技术并不是扎实，遇到些许疑问，希望交流指导。

 配置文件中的logInUrl: "",   以及logInAuthUrl: "",  两个参数应该如何配置为 自己settings 里的创建的 Oath Applications

我有曾尝试过 修改为： https://github.com/login/oauth/authorize?client_id=YOUR_CLIENT_ID&redirect_uri=https://yourusername.github.io/oauth-callback
但是授权登录后，并没有出现文章编辑交互控件。

当然如果您方便有时间的话

感谢！

**Comment by glink25** [comment]
现在使用github登录的能力还不太完善，如果你希望接入的话，可以参考[cloudflare-worker-github-oauth-login](https://github.com/gr2m/cloudflare-worker-github-oauth-login)自己创建一个后端服务，其中前端代码在[这里](https://github.com/glink24/urodele/blob/main/src/components/login.ts)调用了logInAuthUrl指定的后端api，来获取可用的accesstoken

后面会创建一个通用的github app来帮助所有urodele用户完成这一步，但是目前还没有时间做

**Comment by alucardzlh** [comment]
好的，期待，加油！

**Comment by alucardzlh** [comment]
您好，
已经参考github-logIn 项目 并且联动 cloudflare 部署成功了，但是cloudflare中的项目地址 访问404。请问是需要购买域名么？还是需要配置路由规则？
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/00d3fb8d-a3f1-488a-85a0-6d2da9d460c1">

**Comment by briteym** [comment]
@glink25 
hi。
在此处https://github.com/settings/apps/new ，HOMEPAGE URL 和callback url的值该怎么填写？
